services:
  comments-api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./comments-api:/app
    command: ["sh", "-c", "npm install && npm run dev"]

  users-api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./users-api:/app
    command: ["sh", "-c", "npm install && npm run dev"]

  posts-api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./posts-api:/app
    command: ["sh", "-c", "npm install && npm run dev"]

  reverse-proxy:
    image: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - comments-api
      - users-api
      - posts-api